export const Types = {
    LOAD_QUESTIONS_REQUEST: 'questions/LOAD_QUESTIONS_REQUEST',
    LOAD_QUESTIONS_SUCCESS: 'questions/LOAD_QUESTIONS_SUCCESS',
    LOAD_QUESTIONS_ERROR: 'questions/LOAD_QUESTIONS',
    SUBMIT_ANSWER: 'navigation/SUBMIT_ANSWER',
    NEXT_QUESTION: 'navigation/NEXT_QUESTION',
    SHOW_RESULTS: 'navigation/NEXT_QUESTION',
    RESET: 'navigation/RESET',
};

